import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    nav: { gallery: "Gallery", artist: "Artist", commissions: "Commissions", contact: "Contact", cta: "Commission a Piece" },
    home: {
      eyebrow: "Fine Art · Switzerland",
      h1: ["Where", "Darkness", "Becomes Gold"],
      hero_sub: "Or Noir is a Swiss fine-art studio creating singular mixed-media sculptures — built entirely by hand, conceived to endure.",
      hero_tagline: "Bespoke commissions · Limited editions · Worldwide delivery",
      cta1: "View Gallery",
      cta2: "Commission a Piece",
      statement_title: "Fine Art for Extraordinary Spaces",
      statement_body: "Each work emerges from a process of layering — combining skulls, bronze, resin, silk, chains, gears and found objects until something new and irreducible appears. Materials are chosen for their resonance: the weight of metal, the fragility of bone, the flow of latex.",
      craft: "Hand-crafted", craft_desc: "Every piece is made entirely by hand in the Or Noir studio. No mass production, no shortcuts.",
      limited: "Limited editions", limited_desc: "Works are produced in strict editions. Certificates of authenticity accompany every piece.",
      shipping: "Worldwide shipping", shipping_desc: "We work with specialist art handlers to deliver pieces safely to collectors across Europe, the Americas and Asia.",
      selected: "Selected Works",
      selected_sub: "A selection of recent pieces available for acquisition.",
      view_gallery: "View Full Gallery",
      founder_eyebrow: "The Founder",
      founder_bio1: "Founder of Or Noir Art Gallery and one of Europe's most distinctive mixed-media sculptors, Alessio Gentile built an international fine-art brand from a singular vision: that darkness, when mastered, becomes gold.",
      founder_bio2: "His works are held in private collections across four continents. His gallery in Switzerland operates as both a creative studio and a destination for collectors who refuse the ordinary.",
      founder_cta1: "Meet Alessio",
      commission_title: "Begin a Commission",
      commission_sub: "Have a space that demands something extraordinary? We create bespoke works tailored to a specific place and intention.",
      learn_more: "Learn More",
    },
    gallery: {
      title: "Gallery",
      sub: "Original works available for acquisition. Each piece ships with a certificate of authenticity.",
      all: "All",
    },
    artist: {
      eyebrow: "The Artist",
      name: "Alessio Gentile",
      bio1: "Alessio Gentile is not only an artist — he is a visionary entrepreneur who transformed a singular obsession into an internationally recognised fine-art brand. As founder and creative director of Or Noir Art Gallery, he built a self-sustaining studio practice from scratch, establishing a direct-to-collector model that reaches clients across Europe, the Americas, the Middle East, and Asia.",
      bio2: "His leadership is defined by an uncompromising standard of craft and a refusal to scale down the ambition of any piece. Every decision — material, format, edition size — reflects a coherent long-term vision: to create works that appreciate in value precisely because they are irreplaceable.",
      cta: "Commission a Piece",
      on_work: "On the Work",
      quote: '"I don\'t make decoration. I build objects that carry weight — emotional, symbolic, physical. Each material has a reason to be there. The piece is finished when it tells me so — not before."',
      quote_attr: "— Alessio Gentile, Founder & Creative Director",
      bio_title: "Vision & Leadership",
      vision_p1: "Before Or Noir became a gallery, it was a conviction: that there existed an underserved market for handcrafted works of exceptional material complexity — pieces that occupy the territory between fine art and object, between sculpture and symbol.",
      vision_p2: "Alessio built the brand organically, without institutional backing, relying entirely on the quality of the work and an intuitive understanding of what serious collectors want — not trend, but permanence. Or Noir now operates internationally, with bespoke commissions delivered to collectors across four continents.",
      vision_p3: "His entrepreneurial model is as distinctive as his aesthetic: no intermediaries, no compromises on materials, no dilution of the creative process. Every commission is a direct dialogue between artist and client — a collaboration that begins with a conversation and ends with something that will outlast them both.",
      detail1_label: "Studio founded", detail1_desc: "Switzerland — building an international presence from a Swiss studio",
      detail2_label: "International reach", detail2_desc: "Works commissioned by private collectors across Europe, the Americas, the Middle East and Asia",
      detail3_label: "Direct model", detail3_desc: "No galleries, no intermediaries — every work sold directly from the studio",
      detail4_label: "Bespoke commissions", detail4_desc: "Each commission is conceived individually, from initial conversation to delivery",
      process_title: "The Process",
      process_sub: "Every piece passes through hundreds of hours of manual work. Nothing is rushed. Nothing is delegated.",
      process1: "Assembling the armature",
      process2: "Applying resin layers",
      process3: "Final details in the studio",
    },
    commissions: {
      title: "Bespoke Commissions",
      sub: "A commission is the most direct way to bring an Or Noir work into your life.",
      process_title: "The Process",
      form_title: "Begin Your Commission",
      form_sub: "Fill in the form below and Alessio will respond within 48 hours.",
      name: "Full Name", email: "Email Address", budget: "Approximate Budget", timeline: "Desired Timeline", description: "About Your Project",
      send: "Send Enquiry",
      thanks: "Thank you",
      thanks_msg: "Your enquiry has been received. Alessio will be in touch within 48 hours.",
      steps: [
        { title: "Initial Conversation", desc: "We begin with an open conversation about your space, your intentions, and your sensibility. No brief is too loose at this stage." },
        { title: "Concept & Proposal", desc: "Based on our dialogue, Alessio develops a written proposal including material references, dimensional studies, and a production timeline. A deposit of 30% confirms the commission." },
        { title: "Production", desc: "Production timelines range from 8 to 24 weeks depending on complexity. You receive progress updates at key milestones, and we welcome studio visits by appointment." },
        { title: "Completion & Documentation", desc: "The finished work is photographed professionally before shipping. We offer installation guidance for all major works." },
        { title: "Worldwide Delivery", desc: "We ship to collectors across Europe, the Americas, the Middle East, and Asia with specialist art handlers." },
      ],
    },
    contact: {
      title: "Get in Touch",
      sub: "We welcome enquiries from collectors, galleries, architects, and interior designers.",
      studio: "Studio Contact",
      faq_title: "Frequently Asked",
      hours: "Mon – Fri, 9:00 – 17:00",
      hours_label: "Studio Hours (CET)",
      faqs: [
        { q: "Do you sell directly or through galleries?", a: "Works are available directly from the studio and through selected partner galleries. Contact us for current availability." },
        { q: "Can I visit the studio?", a: "Studio visits are by appointment only. We welcome collectors, architects, and interior designers who would like to see works in progress or discuss a commission in person." },
        { q: "How are prices determined?", a: "Prices reflect the complexity of a work, the materials used, and the edition size. We provide pricing on request. Commission budgets are discussed openly from the first conversation." },
        { q: "Do you work with interior designers and architects?", a: "Yes — a significant part of our practice involves collaborating with design and architecture studios on residential and hospitality projects." },
        { q: "Where are you based?", a: "Our studio is based in Switzerland. We work with collectors globally and can arrange studio visits, international shipping, and on-site installation support." },
      ],
    },
    footer: {
      tagline: "Let's create\nsomething timeless.",
      sub: "Every piece begins with a conversation. Reach out to discuss your vision, a commission, or simply to learn more about the work.",
      rights: "Or Noir Fine Art. All rights reserved.",
    }
  },
  it: {
    nav: { gallery: "Galleria", artist: "Artista", commissions: "Commissioni", contact: "Contatto", cta: "Commissiona un'Opera" },
    home: {
      eyebrow: "Belle Arti · Svizzera",
      h1: ["Dove", "L'Oscurità", "Diventa Oro"],
      hero_sub: "Or Noir è uno studio svizzero di belle arti che crea sculture mixed-media singolari — realizzate interamente a mano, concepite per durare.",
      hero_tagline: "Commissioni su misura · Edizioni limitate · Spedizione mondiale",
      cta1: "Vedi la Galleria",
      cta2: "Commissiona un'Opera",
      statement_title: "Belle Arti per Spazi Straordinari",
      statement_body: "Ogni opera emerge da un processo di stratificazione — combinando teschi, bronzo, resina, seta, catene, ingranaggi e oggetti trovati finché non appare qualcosa di nuovo e irriducibile.",
      craft: "Fatto a mano", craft_desc: "Ogni pezzo è realizzato interamente a mano nello studio Or Noir. Nessuna produzione in serie.",
      limited: "Edizioni limitate", limited_desc: "Le opere sono prodotte in edizioni rigorose. Ogni pezzo è accompagnato da un certificato di autenticità.",
      shipping: "Spedizione mondiale", shipping_desc: "Lavoriamo con spedizionieri specializzati per consegnare i pezzi in sicurezza a collezionisti in tutto il mondo.",
      selected: "Opere Selezionate",
      selected_sub: "Una selezione di opere recenti disponibili per l'acquisizione.",
      view_gallery: "Vedi Tutta la Galleria",
      founder_eyebrow: "Il Fondatore",
      founder_bio1: "Fondatore di Or Noir Art Gallery e uno degli scultori mixed-media più distintivi d'Europa, Alessio Gentile ha costruito un marchio internazionale di belle arti da una visione singolare: che l'oscurità, quando padroneggiata, diventa oro.",
      founder_bio2: "Le sue opere sono conservate in collezioni private su quattro continenti. La sua galleria in Svizzera funziona sia come studio creativo che come destinazione per i collezionisti che rifiutano l'ordinario.",
      founder_cta1: "Scopri Alessio",
      commission_title: "Inizia una Commissione",
      commission_sub: "Hai uno spazio che richiede qualcosa di straordinario? Creiamo opere su misura per un luogo e un'intenzione specifici.",
      learn_more: "Scopri di più",
    },
    gallery: { title: "Galleria", sub: "Opere originali disponibili per l'acquisizione.", all: "Tutti" },
    artist: {
      eyebrow: "L'Artista", name: "Alessio Gentile",
      bio1: "Alessio Gentile non è solo un artista — è un imprenditore visionario che ha trasformato un'ossessione singolare in un marchio di belle arti riconosciuto a livello internazionale.",
      bio2: "La sua leadership è definita da uno standard irremovibile di artigianato e da un rifiuto di ridurre l'ambizione di qualsiasi pezzo.",
      cta: "Commissiona un'Opera", on_work: "Sul Lavoro",
      quote: '"Non creo decorazioni. Creo oggetti che portano peso — emotivo, simbolico, fisico. Ogni materiale ha una ragione per essere lì."',
      quote_attr: "— Alessio Gentile, Fondatore e Direttore Creativo", bio_title: "Visione e Leadership",
      vision_p1: "Prima che Or Noir diventasse una galleria, era una convinzione: che esistesse un mercato sottoservito per opere artigianali di eccezionale complessità materiale.",
      vision_p2: "Alessio ha costruito il marchio organicamente, senza supporto istituzionale, affidandosi interamente alla qualità del lavoro.",
      vision_p3: "Il suo modello imprenditoriale è altrettanto distintivo della sua estetica: nessun intermediario, nessun compromesso sui materiali.",
      detail1_label: "Studio fondato", detail1_desc: "Svizzera — costruendo una presenza internazionale da uno studio svizzero",
      detail2_label: "Portata internazionale", detail2_desc: "Opere commissionate da collezionisti privati in tutto il mondo",
      detail3_label: "Modello diretto", detail3_desc: "Nessuna galleria, nessun intermediario — ogni opera venduta direttamente dallo studio",
      detail4_label: "Commissioni su misura", detail4_desc: "Ogni commissione è concepita individualmente, dalla conversazione iniziale alla consegna",
      process_title: "Il Processo",
      process_sub: "Ogni pezzo attraversa centinaia di ore di lavoro manuale. Nulla è affrettato. Nulla è delegato.",
      process1: "Assemblaggio dell'armatura",
      process2: "Applicazione degli strati di resina",
      process3: "Dettagli finali nello studio",
    },
    commissions: {
      title: "Commissioni su Misura", sub: "Una commissione è il modo più diretto per portare un'opera Or Noir nella tua vita.",
      process_title: "Il Processo", form_title: "Inizia la Tua Commissione", form_sub: "Compila il modulo e Alessio risponderà entro 48 ore.",
      name: "Nome Completo", email: "Indirizzo Email", budget: "Budget Approssimativo", timeline: "Tempistica Desiderata", description: "Il Tuo Progetto",
      send: "Invia Richiesta", thanks: "Grazie", thanks_msg: "La tua richiesta è stata ricevuta. Alessio ti risponderà entro 48 ore.",
      steps: [
        { title: "Conversazione Iniziale", desc: "Iniziamo con una conversazione aperta sul tuo spazio e le tue intenzioni." },
        { title: "Concetto e Proposta", desc: "Alessio sviluppa una proposta scritta con riferimenti materiali e tempistiche. Un deposito del 30% conferma la commissione." },
        { title: "Produzione", desc: "I tempi di produzione vanno da 8 a 24 settimane. Riceverai aggiornamenti ai principali traguardi." },
        { title: "Completamento e Documentazione", desc: "L'opera finita viene fotografata professionalmente prima della spedizione." },
        { title: "Consegna Mondiale", desc: "Spediamo a collezionisti in Europa, Americhe, Medio Oriente e Asia con spedizionieri specializzati." },
      ],
    },
    contact: {
      title: "Contattaci", sub: "Accogliamo richieste da collezionisti, gallerie, architetti e designer d'interni.",
      studio: "Contatto Studio", faq_title: "Domande Frequenti",
      hours: "Lun – Ven, 9:00 – 17:00", hours_label: "Orari Studio (CET)",
      faqs: [
        { q: "Vendete direttamente o tramite gallerie?", a: "Le opere sono disponibili direttamente dallo studio e attraverso gallerie partner selezionate." },
        { q: "Posso visitare lo studio?", a: "Le visite allo studio sono solo su appuntamento." },
        { q: "Come vengono determinati i prezzi?", a: "I prezzi riflettono la complessità dell'opera, i materiali utilizzati e la dimensione dell'edizione." },
        { q: "Lavorate con designer d'interni e architetti?", a: "Sì — una parte significativa della nostra pratica coinvolge la collaborazione con studi di design e architettura." },
        { q: "Dove siete?", a: "Il nostro studio è in Svizzera. Lavoriamo con collezionisti a livello globale." },
      ],
    },
    footer: {
      tagline: "Creiamo qualcosa\ndi eterno.",
      sub: "Tutto inizia con una conversazione. Contattaci per parlare della tua visione o di una commissione.",
      rights: "Or Noir Fine Art. Tutti i diritti riservati.",
    }
  },
  de: {
    nav: { gallery: "Galerie", artist: "Künstler", commissions: "Aufträge", contact: "Kontakt", cta: "Werk in Auftrag geben" },
    home: {
      eyebrow: "Bildende Kunst · Schweiz",
      h1: ["Wo", "Dunkelheit", "Zu Gold Wird"],
      hero_sub: "Or Noir ist ein Schweizer Kunstatelier, das einzigartige Mixed-Media-Skulpturen erschafft — vollständig von Hand gefertigt, konzipiert um zu dauern.",
      hero_tagline: "Massgeschneiderte Aufträge · Limitierte Auflagen · Weltweiter Versand",
      cta1: "Galerie ansehen",
      cta2: "Werk in Auftrag geben",
      statement_title: "Bildende Kunst für aussergewöhnliche Räume",
      statement_body: "Jedes Werk entsteht durch einen Schichtungsprozess — Kombination von Schädeln, Bronze, Harz, Seide, Ketten, Zahnrädern und Fundstücken.",
      craft: "Handgefertigt", craft_desc: "Jedes Stück wird vollständig von Hand im Or Noir Atelier hergestellt.",
      limited: "Limitierte Auflagen", limited_desc: "Werke werden in strengen Auflagen produziert. Jedes Stück wird mit einem Echtheitszertifikat geliefert.",
      shipping: "Weltweiter Versand", shipping_desc: "Wir arbeiten mit spezialisierten Kunstspediteuren zusammen.",
      selected: "Ausgewählte Werke",
      selected_sub: "Eine Auswahl aktueller Werke, die zum Erwerb verfügbar sind.",
      view_gallery: "Gesamte Galerie",
      founder_eyebrow: "Der Gründer",
      founder_bio1: "Als Gründer der Or Noir Art Gallery und einer der markantesten Mixed-Media-Bildhauer Europas hat Alessio Gentile eine internationale Fine-Art-Marke aus einer einzigartigen Vision aufgebaut: dass Dunkelheit, wenn sie gemeistert wird, zu Gold wird.",
      founder_bio2: "Seine Werke befinden sich in Privatsammlungen auf vier Kontinenten. Seine Galerie in der Schweiz fungiert sowohl als Kreativstudio als auch als Destination für Sammler, die das Gewöhnliche ablehnen.",
      founder_cta1: "Alessio kennenlernen",
      commission_title: "Auftrag beginnen",
      commission_sub: "Haben Sie einen Raum, der etwas Aussergewöhnliches verlangt? Wir erstellen massgeschneiderte Werke.",
      learn_more: "Mehr erfahren",
    },
    gallery: { title: "Galerie", sub: "Originalwerke zum Erwerb. Jedes Stück wird mit einem Echtheitszertifikat geliefert.", all: "Alle" },
    artist: {
      eyebrow: "Der Künstler", name: "Alessio Gentile",
      bio1: "Alessio Gentile ist nicht nur ein Künstler — er ist ein visionärer Unternehmer, der eine einzigartige Obsession in eine international anerkannte Fine-Art-Marke verwandelt hat.",
      bio2: "Seine Führung ist geprägt von einem kompromisslosen Qualitätsstandard und der Weigerung, den Ehrgeiz eines Werkes zu reduzieren.",
      cta: "Werk in Auftrag geben", on_work: "Über die Arbeit",
      quote: '"Ich mache keine Dekoration. Ich mache Objekte, die Gewicht tragen — emotional, symbolisch, physisch. Jedes Material hat einen Grund, dort zu sein."',
      quote_attr: "— Alessio Gentile, Gründer & Kreativdirektor", bio_title: "Vision & Führung",
      vision_p1: "Bevor Or Noir eine Galerie wurde, war es eine Überzeugung: dass es einen unterversorgten Markt für handgefertigte Werke von aussergewöhnlicher materieller Komplexität gab.",
      vision_p2: "Alessio baute die Marke organisch auf, ohne institutionelle Unterstützung, und verliess sich ausschliesslich auf die Qualität der Arbeit.",
      vision_p3: "Sein unternehmerisches Modell ist ebenso unverwechselbar wie seine Ästhetik: keine Vermittler, keine Kompromisse bei Materialien.",
      detail1_label: "Atelier gegründet", detail1_desc: "Schweiz — Aufbau einer internationalen Präsenz aus einem Schweizer Atelier",
      detail2_label: "Internationale Reichweite", detail2_desc: "Werke von Privatsammlern auf der ganzen Welt in Auftrag gegeben",
      detail3_label: "Direktes Modell", detail3_desc: "Keine Galerien, keine Vermittler — jedes Werk direkt aus dem Atelier verkauft",
      detail4_label: "Massgeschneiderte Aufträge", detail4_desc: "Jeder Auftrag wird individuell konzipiert, vom ersten Gespräch bis zur Lieferung",
      process_title: "Der Prozess",
      process_sub: "Jedes Stück durchläuft Hunderte von Stunden manueller Arbeit. Nichts wird überstürzt. Nichts wird delegiert.",
      process1: "Montage des Armaturenrahmens",
      process2: "Auftragen der Harzschichten",
      process3: "Letzte Details im Atelier",
    },
    commissions: {
      title: "Massgeschneiderte Aufträge", sub: "Ein Auftrag ist der direkteste Weg, ein Or Noir Werk in Ihr Leben zu bringen.",
      process_title: "Der Prozess", form_title: "Auftrag beginnen", form_sub: "Füllen Sie das Formular aus und Alessio antwortet innerhalb von 48 Stunden.",
      name: "Vollständiger Name", email: "E-Mail-Adresse", budget: "Ungefähres Budget", timeline: "Gewünschter Zeitplan", description: "Über Ihr Projekt",
      send: "Anfrage senden", thanks: "Danke", thanks_msg: "Ihre Anfrage wurde erhalten. Alessio wird sich innerhalb von 48 Stunden melden.",
      steps: [
        { title: "Erstes Gespräch", desc: "Wir beginnen mit einem offenen Gespräch über Ihren Raum und Ihre Absichten." },
        { title: "Konzept und Angebot", desc: "Alessio entwickelt ein schriftliches Angebot mit Materialreferenzen und Zeitplan. Eine Anzahlung von 30% bestätigt den Auftrag." },
        { title: "Produktion", desc: "Produktionszeiten reichen von 8 bis 24 Wochen. Sie erhalten Fortschrittsupdates bei wichtigen Meilensteinen." },
        { title: "Fertigstellung und Dokumentation", desc: "Das fertige Werk wird professionell fotografiert, bevor es versandt wird." },
        { title: "Weltweite Lieferung", desc: "Wir liefern an Sammler in Europa, Amerika, dem Nahen Osten und Asien." },
      ],
    },
    contact: {
      title: "Kontakt aufnehmen", sub: "Wir begrüssen Anfragen von Sammlern, Galerien, Architekten und Innenarchitekten.",
      studio: "Studiokontakt", faq_title: "Häufige Fragen",
      hours: "Mo – Fr, 9:00 – 17:00", hours_label: "Atelierzeiten (MEZ)",
      faqs: [
        { q: "Verkaufen Sie direkt oder über Galerien?", a: "Werke sind direkt aus dem Atelier und über ausgewählte Partnergalerien erhältlich." },
        { q: "Kann ich das Atelier besuchen?", a: "Atelierbesuche sind nur nach Vereinbarung möglich." },
        { q: "Wie werden die Preise festgelegt?", a: "Die Preise spiegeln die Komplexität eines Werkes, die verwendeten Materialien und die Auflagengrösse wider." },
        { q: "Arbeiten Sie mit Innenarchitekten und Architekten zusammen?", a: "Ja — ein bedeutender Teil unserer Praxis beinhaltet die Zusammenarbeit mit Design- und Architekturbüros." },
        { q: "Wo befinden Sie sich?", a: "Unser Atelier befindet sich in der Schweiz. Wir arbeiten weltweit mit Sammlern zusammen." },
      ],
    },
    footer: {
      tagline: "Lassen Sie uns etwas\nZeitloses schaffen.",
      sub: "Alles beginnt mit einem Gespräch. Kontaktieren Sie uns, um Ihre Vision zu besprechen.",
      rights: "Or Noir Fine Art. Alle Rechte vorbehalten.",
    }
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}